### ISSUE TITLE
https Keep-Alive support ?

### ISSUE THREAD

**Issue by ruslanx3m** [TooTallNate/proxy-agents#110]
Keep-Alive support ?

**Comment by ArturAralin** [comment]
Look on my PR https://github.com/TooTallNate/node-https-proxy-agent/pull/112

**Comment by giy-debug** [comment]
I have switched to using this library:
https://github.com/mknj/node-keepalive-proxy-agent/blob/master/index.js
Note that it's configured with `host` instead of `hostname`.

Looking at the source code here I think it's flawed because it creates a new socket for every request and thus it is repeating the TLS handshake with every request. Would be a major revamp to implement. Also I don't understand why it is not extending the native https.Agent.

**Comment by Nisthar** [comment]
@giy-debug does it work with axios?

**Comment by TooTallNate** [comment]
`keepAlive: true` is finally here! https://github.com/TooTallNate/proxy-agents/pull/147
