### ISSUE TITLE
Keep-Alive Support

### ISSUE THREAD

**Issue by julianduque** [TooTallNate/proxy-agents#18]
There is plans to add Keep-Alive support to this agent? or do you know any tunneled proxy implementation with keep-alive / persistent connection support?

**Comment by TooTallNate** [comment]
Hey @julianduque. Keep-Alive is not implemented at this time. The plan is to [implement it in `agent-base`](https://github.com/TooTallNate/node-agent-base/issues/5), but haven't gotten around to it yet.

**Comment by julianduque** [comment]
Thanks @TooTallNate ! we can close it here too to avoid duplicates!

**Comment by euangordon** [comment]
#18 and #29 both are closed because they are duplicates of each other. Is there an issue tracking this now?

**Comment by julianduque** [comment]
@euangordon I re-opened since it seems isn't fixed? Can you confirm @TooTallNate?

**Comment by euangordon** [comment]
@julianduque @TooTallNate it seems to be working fine. I was looking for supporting information around configuration and came across these two issues both of which were closed as duplicated of one another, without mentioning if the issue was resolved.

Yesterday I was using it with Fiddler without any issues.

**Comment by terion-name** [comment]
Such a required feature and nothing for 4 years :(
